// <auto-generated />
namespace DbProvides.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SomeChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SomeChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202001011707164_SomeChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
